/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : MotRigGetSpeed.h
**     Project   : Sunny3
**     Processor : MC9S12XS128MAA
**     Component : BitIO
**     Version   : Component 02.075, Driver 03.14, CPU db: 3.00.019
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2014/5/18, 3:19
**     Abstract  :
**         This component "BitIO" implements an one-bit input/output.
**         It uses one bit/pin of a port.
**         Note: This component is set to work in Output direction only.
**         Methods of this component are mostly implemented as a macros
**         (if supported by target language and compiler).
**     Settings  :
**         Used pin                    :
**             ----------------------------------------------------
**                Number (on package)  |    Name
**             ----------------------------------------------------
**                       2             |  PP2_KWP2_PWM2_IOC2_TxD1
**             ----------------------------------------------------
**
**         Port name                   : P
**
**         Bit number (in port)        : 2
**         Bit mask of the port        : $0004
**
**         Initial direction           : Output (direction cannot be changed)
**         Initial output value        : 1
**         Initial pull option         : up
**
**         Port data register          : PTP       [$0258]
**         Port control register       : DDRP      [$025A]
**
**         Optimization for            : speed
**     Contents  :
**         ClrVal - void MotRigGetSpeed_ClrVal(void);
**         SetVal - void MotRigGetSpeed_SetVal(void);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef MotRigGetSpeed_H_
#define MotRigGetSpeed_H_

/* MODULE MotRigGetSpeed. */

  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#pragma CODE_SEG MotRigGetSpeed_CODE
/*
** ===================================================================
**     Method      :  MotRigGetSpeed_ClrVal (component BitIO)
**
**     Description :
**         This method clears (sets to zero) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define MotRigGetSpeed_ClrVal() ( \
    (void)clrReg8Bits(PTP, 0x04U)      /* PTP2=0x00U */ \
  )

/*
** ===================================================================
**     Method      :  MotRigGetSpeed_SetVal (component BitIO)
**
**     Description :
**         This method sets (sets to one) the output value.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
#define MotRigGetSpeed_SetVal() ( \
    (void)setReg8Bits(PTP, 0x04U)      /* PTP2=0x01U */ \
  )

#pragma CODE_SEG DEFAULT

/* END MotRigGetSpeed. */
#endif /* #ifndef __MotRigGetSpeed_H_ */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
