/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : PA.h
**     Project   : Sunny3
**     Processor : MC9S12XS128MAA
**     Component : ByteIO
**     Version   : Component 02.058, Driver 03.15, CPU db: 3.00.019
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2014/5/18, 3:19
**     Abstract  :
**         This component "ByteIO" implements an one-byte input/output.
**         It uses one 8-bit port.
**         Note: This component is set to work in Input direction only.
**         Methods of this component are mostly implemented as a macros 
**         (if supported by target langauage and compiler).
**     Settings  :
**         Port name                   : A
**
**         Initial direction           : Input (direction cannot be changed)
**         Initial output value        : 0 = 000H
**         Initial pull option         : up
**
**         8-bit data register         : PORTA     [$0000]
**         8-bit control register      : DDRA      [$0002]
**
**             ----------------------------------------------------
**                   Bit     |   Pin   |   Name
**             ----------------------------------------------------
**                    0      |    41   |   PA0
**                    1      |    42   |   PA1
**                    2      |    43   |   PA2
**                    3      |    44   |   PA3
**                    4      |    45   |   PA4
**                    5      |    46   |   PA5
**                    6      |    47   |   PA6
**                    7      |    48   |   PA7
**             ----------------------------------------------------
**     Contents  :
**         No public methods
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef PA_H_
#define PA_H_

/* MODULE PA. */

  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#pragma CODE_SEG PA_CODE
#pragma CODE_SEG DEFAULT

/* END PA. */
#endif /* #ifndef __PA_H_ */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
