/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Pulse.h
**     Project   : Sunny3
**     Processor : MC9S12XS128MAA
**     Component : PulseAccumulator
**     Version   : Component 01.185, Driver 01.19, CPU db: 3.00.019
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2014/5/18, 3:19
**     Abstract  :
**     Settings  :
**             Pulse accumulator       : PACNT
**
**              Pulse accumulator      : Enabled
**              Events                 : Enabled
**
**         Timer registers
**              Counter                : PACNT     [$0062]
**              Mode                   : PACTL     [$0060]
**              Run                    : PACTL     [$0060]
**              Prescaler              : PACTL     [$0060]
**
**         User handling procedure     : not specified
**
**     Contents  :
**         ResetCounter    - void Pulse_ResetCounter(void);
**         GetCounterValue - Pulse_TCounterValue Pulse_GetCounterValue(void);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

#ifndef __Pulse
#define __Pulse

/* MODULE Pulse. */

#include "Cpu.h"

#pragma CODE_SEG Pulse_CODE
#pragma DATA_SEG Pulse_DATA            /* Select data segment "Pulse_DATA" */

#ifndef __BWUserType_Pulse_TCounterValue
#define __BWUserType_Pulse_TCounterValue
typedef word Pulse_TCounterValue;      /* Counter value, width depends on selected peripheal. */
#endif

#define Pulse_ResetCounter() ( \
  PACNT = 0U\
)
/*
** ===================================================================
**     Method      :  Pulse_ResetCounter (component PulseAccumulator)
**
**     Description :
**         This method resets the pulse accumulator counter (sets to
**         zero).
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define Pulse_GetCounterValue() (PACNT)
/*
** ===================================================================
**     Method      :  Pulse_GetCounterValue (component PulseAccumulator)
**
**     Description :
**         This method returns the content of the pulse accumulator
**         counter.
**     Parameters  : None
**     Returns     :
**         ---             - Content of the counter register.
** ===================================================================
*/

void Pulse_Init(void);
/*
** ===================================================================
**     Method      :  Pulse_Init (component PulseAccumulator)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

#pragma DATA_SEG DEFAULT               /* Select data segment "DEFAULT" */
#pragma CODE_SEG DEFAULT

/* END Pulse. */

#endif /* ifndef __Pulse */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
