/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : Pulse.c
**     Project   : Sunny3
**     Processor : MC9S12XS128MAA
**     Component : PulseAccumulator
**     Version   : Component 01.185, Driver 01.19, CPU db: 3.00.019
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2014/5/18, 3:19
**     Abstract  :
**     Settings  :
**             Pulse accumulator       : PACNT
**
**              Pulse accumulator      : Enabled
**              Events                 : Enabled
**
**         Timer registers
**              Counter                : PACNT     [$0062]
**              Mode                   : PACTL     [$0060]
**              Run                    : PACTL     [$0060]
**              Prescaler              : PACTL     [$0060]
**
**         User handling procedure     : not specified
**
**     Contents  :
**         ResetCounter    - void Pulse_ResetCounter(void);
**         GetCounterValue - Pulse_TCounterValue Pulse_GetCounterValue(void);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE Pulse. */

#include "Pulse.h"

#pragma DATA_SEG Pulse_DATA            /* Select data segment "Pulse_DATA" */
#pragma CODE_SEG Pulse_CODE

/*
** ===================================================================
**     Method      :  Pulse_ResetCounter (component PulseAccumulator)
**
**     Description :
**         This method resets the pulse accumulator counter (sets to
**         zero).
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
/*
void Pulse_ResetCounter(void)

**      This method is implemented as macro. See Pulse.h file.      **
*/

/*
** ===================================================================
**     Method      :  Pulse_GetCounterValue (component PulseAccumulator)
**
**     Description :
**         This method returns the content of the pulse accumulator
**         counter.
**     Parameters  : None
**     Returns     :
**         ---             - Content of the counter register.
** ===================================================================
*/
/*
Pulse_TCounterValue Pulse_GetCounterValue(void)

**      This method is implemented as macro. See Pulse.h file.      **
*/

/*
** ===================================================================
**     Method      :  Pulse_Init (component PulseAccumulator)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void Pulse_Init(void)
{
  /* PACTL: ??=0,PAEN=1,PAMOD=0,PEDGE=1,CLK1=0,CLK0=0,PAOVI=0,PAI=0 */
  setReg8(PACTL, 0x50U);               /* Set up pulse accumulator mode */ 
}

/* END Pulse. */

/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
