/** ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename  : SW.c
**     Project   : Sunny3
**     Processor : MC9S12XS128MAA
**     Component : ByteIO
**     Version   : Component 02.058, Driver 03.15, CPU db: 3.00.019
**     Compiler  : CodeWarrior HCS12X C Compiler
**     Date/Time : 2014/5/18, 3:19
**     Abstract  :
**         This component "ByteIO" implements an one-byte input/output.
**         It uses one 8-bit port.
**         Note: This component is set to work in Input direction only.
**         Methods of this component are mostly implemented as a macros 
**         (if supported by target langauage and compiler).
**     Settings  :
**         Port name                   : AD0L
**
**         Initial direction           : Input (direction cannot be changed)
**         Initial output value        : 0 = 000H
**         Initial pull option         : up
**
**         8-bit data register         : PT1AD0    [$0271]
**         8-bit control register      : DDR1AD0   [$0273]
**
**             ----------------------------------------------------
**                   Bit     |   Pin   |   Name
**             ----------------------------------------------------
**                    0      |    51   |   PAD00_AN00
**                    1      |    52   |   PAD01_AN01
**                    2      |    53   |   PAD02_AN02
**                    3      |    54   |   PAD03_AN03
**                    4      |    55   |   PAD04_AN04
**                    5      |    56   |   PAD05_AN05
**                    6      |    57   |   PAD06_AN06
**                    7      |    58   |   PAD07_AN07
**             ----------------------------------------------------
**     Contents  :
**         GetVal - byte SW_GetVal(void);
**         GetBit - bool SW_GetBit(byte Bit);
**
**     Copyright : 1997 - 2010 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/

/* MODULE SW. */

#include "SW.h"
  /* Including shared modules, which are used in the whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
#include "Cpu.h"

#pragma DATA_SEG SW_DATA               /* Select data segment "SW_DATA" */
#pragma CODE_SEG SW_CODE
#pragma CONST_SEG SW_CONST             /* Constant section for this module */
/*
** ===================================================================
**     Method      :  SW_GetMsk (component ByteIO)
**
**     Description :
**         The method returns a bit mask which corresponds to the 
**         required bit position.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
static const byte SW_Table[8U] = {
  0x01U, 0x02U, 0x04U, 0x08U, 0x10U, 0x20U, 0x40U, 0x80U
};                                     /* Table of mask constants */

static byte SW_GetMsk (byte PinIndex)
{
  return (byte)((PinIndex<8U) ? SW_Table[PinIndex] : 0U); /* Check range and return appropriate bit mask */
}

/*
** ===================================================================
**     Method      :  SW_GetVal (component ByteIO)
**
**     Description :
**         This method returns an input value.
**           a) direction = Input  : reads the input value from the
**                                   pins and returns it
**           b) direction = Output : returns the last written value
**         Note: This component is set to work in Input direction only.
**     Parameters  : None
**     Returns     :
**         ---        - Input value (0 to 255)
** ===================================================================
*/
/*
byte SW_GetVal(void)

**  This method is implemented as a macro. See SW.h file.  **
*/

/*
** ===================================================================
**     Method      :  SW_GetBit (component ByteIO)
**
**     Description :
**         This method returns the specified bit of the input value.
**           a) direction = Input  : reads the input value from pins
**                                   and returns the specified bit
**           b) direction = Output : returns the specified bit
**                                   of the last written value
**         Note: This component is set to work in Input direction only.
**     Parameters  :
**         NAME       - DESCRIPTION
**         Bit        - Number of the bit to read (0 to 7)
**     Returns     :
**         ---        - Value of the specified bit (FALSE or TRUE)
**                      FALSE = "0" or "Low", TRUE = "1" or "High"
** ===================================================================
*/
bool SW_GetBit(byte Bit)
{
  byte const Mask = SW_GetMsk(Bit);    /* Temporary variable - bit mask to test */
  return (bool)(((getReg8(PT1AD0) & Mask) == Mask) ? 1U : 0U); /* Test if specified bit of port data register is set */
}


/* END SW. */
/*
** ###################################################################
**
**     This file was created by Processor Expert 3.02 [04.44]
**     for the Freescale HCS12X series of microcontrollers.
**
** ###################################################################
*/
